
import '../../../assets/images/svg/svg-title.svg'
import '../../../assets/images/svg/svg-header.svg'
import '../../../assets/images/svg/svg-bold.svg'
import '../../../assets/images/svg/svg-underline.svg'
import '../../../assets/images/svg/svg-center.svg'
import '../../../assets/images/svg/svg-quote.svg'
import '../../../assets/images/svg/svg-list.svg'
import '../../../assets/images/svg/svg-link.svg'
import '../../../assets/images/svg/svg-image.svg'
import '../../../assets/images/svg/svg-code.svg'
import '../../../assets/images/svg/svg-codes.svg'
import '../../../assets/images/svg/svg-table.svg'
import '../../../assets/images/svg/svg-undo.svg'
import '../../../assets/images/svg/svg-redo.svg'
import '../../../assets/images/svg/svg-save.svg'
import '../../../assets/images/svg/svg-fullscreen.svg'
